  __description__:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: __subnet__
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: __interface__